import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppNavProvider } from "./contexts/AppNavContext";
import { LocaleProvider } from "./contexts/LocaleContext";
import GlobalNav from "./GlobalNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// VELIS iPhone 16 Pro hedefli, sadece portre bir uygulama olarak
// tasarlandı (bkz. AGENTS.md üretim hazırlığı fazı). 393px genişlik hedef
// cihazın mantıksal genişliğiyle birebir eşleştiği için bu, gerçek cihazda
// hiçbir görsel değişiklik yaratmıyor - sadece diğer ekran genişliklerinde
// (masaüstü/tablet) responsive davranışı devre dışı bırakıyor.
export const viewport: Viewport = {
  width: 393,
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <LocaleProvider>
          <AppNavProvider>
            {children}
            <GlobalNav />
          </AppNavProvider>
        </LocaleProvider>
      </body>
    </html>
  );
}
